# -*- coding: utf-8 -*-
"""caesarcipher.ipymb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLpDT5kC-5fySIgYrCfK3os7B7W02uAl
"""

from typing import KeysView
def generate_key(n):
  letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  key = {}
  cnt = 0
  for c in letters:
    key[c] = letters((cnt+n)%len(letters))
    cnt += 1
    return key

    def encrypt(key,message):
      cipher = ""
      for c in message:
        if c in key:
          cipher += key[c]
        else:
          cipher+= c
          return cipher


    key = generate_key(3)
    print(key)
    message="YOU ARE AWESOME"
    cipher = encrypt(key,message)
    print(cipher)